# -*- coding: utf-8 -*-
"""Project7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jV16mrUZBACke6xdLKQJwQ5Yo6KhxIg0

# **NOTE:** Use File > Save a copy in Drive to make a copy before doing anything else

# Project 7: Student Habits vs Academic Performance Analysis

#### Overview

This project analyzes the relationship between student lifestyle habits and academic performance using a comprehensive dataset from Kaggle. The dataset contains information about 1,000 students and includes 16 variables covering various aspects of student life, including study habits, social media usage, sleep patterns, diet quality, exercise frequency, and academic outcomes.

The analysis focuses on understanding how different study patterns correlate with exam performance.The project demonstrates fundamental data analysis skills including data cleaning, statistical calculations, and comparative analysis using Python and pandas.
"""

# Install dependencies as needed:
# pip install kagglehub[pandas-datasets]
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file you'd like to load
# Update file_path to point to the specific file within the dataset
file_path = "student_habits_performance.csv"

# Load the latest version
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "jayaantanaath/student-habits-vs-academic-performance",
  file_path,
  # Provide any additional arguments like
  # sql_query or pandas_kwargs. See the
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

print("First 5 records:", df.head())

one_col = df['age']

type(one_col)

df.info()

df.shape

df.columns

"""### clean the data"""

df.isnull().sum()

"""This checks how many missing (NaN) values are in each column of the DataFrame. Based on the output:

All columns have 0 missing values except for parental_education_level, which has 91 missing values.

The dataset is mostly clean, but you do need to clean or handle the missing data in the parental_education_level column.

#### Fill with a default or common value

#### drop rows with missing values
"""

df.dropna(subset=['parental_education_level'], inplace=True)

# checking the data again
df.isnull().sum()

"""### Questions to Answer

Please find the answer for the following questoins.

1. Find the average study hours per day for all students. Please create a code cell below this to answer the question.(0.5 point)
"""

# finding the average of the column: 'study_hours_per_day'
average = (df['study_hours_per_day']).mean()
print(average)

"""2. Identify the student who studies MOST hours per day. Please create a code cell below to answer the question.(0.5 point)"""

# finds the max of study_hours_per_day and then finds which student id matches that max number
max_study_hours = df['study_hours_per_day'].max()
student_most_study_hours = df[df['study_hours_per_day'] == max_study_hours]

# Display the student(s) who study the most hours
print(student_most_study_hours[['student_id', 'study_hours_per_day']])

"""3. Count how many students study more than 6 hours per day. Please create a code cell below this to answer the question.(0.5 point)"""

# finds the number of students who study more than 6 hours per day
more_than_6_hours = df[df['study_hours_per_day'] > 6]
count_more_than_6_hours = more_than_6_hours.shape[0]
print(count_more_than_6_hours)

"""4. What is the percentage of students who study more than 6 hours per day. Please create a code cell below this to answer the question.(0.5 point)"""

# uses the variable count_more_than_6_hours from previous code cell, divides by total number of student,
# and then multiples by 100 the get a percentage
total_students = df.shape[0]
percentage_more_than_6_hours = (count_more_than_6_hours / total_students) * 100

print(percentage_more_than_6_hours)

"""5. Calculate what percentage of students study less than 2 hours per day. Please create a code cell below this to answer the question.(0.5 point)"""

# uses same methods from questions 3 and 4
# finds students who have studied less than 2 hours and then finds the percentage
less_than_2_hours = df[df['study_hours_per_day'] < 2]
count_less_than_2_hours = less_than_2_hours.shape[0]
total_students = df.shape[0]
percentage_less_than_2_hours = (count_less_than_2_hours / total_students) * 100

print(percentage_less_than_2_hours)

"""6. Do students who study more than 5 hours per day have higher exam scores on average? Please create a code cell below to answer this question. (0.5 point)"""

# finding the average of students exam scores that studied less than or equal to 5 hours
less_than_5_hours = df[df['study_hours_per_day'] <= 5]
average_score_less_than_5_hours = less_than_5_hours['exam_score'].mean()

# finding the average of students exam scores that studied more than 5 hours
more_than_5_hours = df[df['study_hours_per_day'] > 5]
average_score_more_than_5_hours = more_than_5_hours['exam_score'].mean()

# printing out both averages so we can compare results
print("Average exam score for students who study less than or equal to 5 hours per day:", average_score_less_than_5_hours)
print("Average exam score for students who study more than 5 hours per day:", average_score_more_than_5_hours)

"""7. Use "Explain code" for the code you produced for Question 6 and summarize in your own words to show that you understood the code Gemini produced. Please create a text cell below to answer this question. (0.5 point)

**For both more than 5 hours and less than 5 hours, we created a new table that only have values of that specification. After getting the new table, we get the mean of the column 'exam_score' to get the average. Finally, it prints both averages so we can compare the two.**

8. The codes produced to answer the questions use "vectorization"? Please justify your answer with an example. Please create a text cell below to answer this question. (0.5 point)

**Yes, the code uses vectorization. This means operations are applied to entire columns or data structures at once, instead of processing data item by item in a loop. This is much faster and more efficient. An example of this would be when we filtered students studying more than 6 hours: more_than_6_hours = df[df['study_hours_per_day'] > 6]. The condition df['study_hours_per_day'] > 6 is applied to every value in the 'study_hours_per_day' column at the same time. it runs this comparison across the entire column, returning a True/False for each student without needing an loop.**
"""